### ISSUE TITLE
UI Tests that edit Account Details

### ISSUE THREAD

**Issue by phil-davis** [phil-davis/mautic#22]
- [x] change first name and/or last name and make sure they are displayed correctly. #25 
- [x] change password (including invalid entry) #26 
- [x] select locale/language #29

**Comment by phil-davis** [comment]
Step 1: fix the underlying Mautic/doctrine code that claims to be able to reload fixtures - PR #23

**Comment by phil-davis** [comment]
Step 2: provide infrastructure to reload fixtures before any scenario that is tagged "fixtures" - PR #24

**Comment by phil-davis** [comment]
Step 3: Implement the actual tests - done
